drop database saga_db;
CREATE DATABASE saga_db;

USE saga_db;

CREATE TABLE TABLE_A (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL
);

CREATE TABLE TABLE_B (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL ,
  address VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES TABLE_A(id)
);

CREATE TABLE TABLE_C (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL ,
  payment_method VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES TABLE_A(id)
);

CREATE TABLE SAGA_LOG (
  id INT AUTO_INCREMENT PRIMARY KEY,
  saga_id VARCHAR(100),
  service VARCHAR(100),
  status VARCHAR(10),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
